name: CI with Raspberry Pi-Compatible Build Environment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build build container
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 \
            -t local-build-container:latest \
            ./build-environment --load

      - name: Build and package inside build container
        uses: addnab/docker-run-action@v3
        with:
          image: local-build-container:latest
          options: --rm -v ${{ github.workspace }}:/app -w /app
          run: |
            appimageBuild/all.sh

      - name: Release eink.AppImage
        uses: softprops/action-gh-release@v1
        with:
          files: eink.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
